### ISSUE TITLE
额....能先介绍下使用场景和演示效果吗

### ISSUE THREAD

**Issue by xiaolushuo** [schaepher/noty#2]
额....大概是我的理解能力有点差哈，看了半天使用说明，有点云里雾里的

**Comment by schaepher** [comment]
> 额....大概是我的理解能力有点差哈，看了半天使用说明，有点云里雾里的

@xiaolushuo 这个项目是让你可以通过个人微信去发消息给你自己搭建的服务器，以及接收来自服务器的消息。使用场景要看你想用这个通信渠道做些什么了。比如我会把我想看的公众号文章转发给我的服务器， 让它保存成 PDF。

简单的演示效果是：
![image](https://github.com/schaepher/noty/assets/14355289/ad3117a6-8c26-4235-8fc8-49d1b6285af6)

README.md 上的是企业微信应用的配置流程，跟着一步步做就行了，不需要理解啥。
