### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by FinchSaXY** [schaepher/noty#3]
不会编译，用go build出现错误
go: downloading github.com/gin-gonic/gin v1.7.7
go: downloading github.com/flytam/filenamify v1.1.3
go: downloading github.com/workweixin/weworkapi_golang v0.0.0-20200831071321-c1fdfd3d6e7d
main.go:13:2: github.com/gin-gonic/gin@v1.7.7: Get "https://proxy.golang.org/github.com/gin-gonic/gin/@v/v1.7.7.zip": dial tcp: lookup proxy.golang.org: no such host
qiyewechat\agent_echo.go:9:2: github.com/flytam/filenamify@v1.1.3: Get "https://proxy.golang.org/github.com/flytam/filenamify/@v/v1.1.3.zip": dial tcp: lookup proxy.golang.org: no such host
qiyewechat\agent.go:7:2: github.com/workweixin/weworkapi_golang@v0.0.0-20200831071321-c1fdfd3d6e7d: Get "https://proxy.golang.org/github.com/workweixin/weworkapi_golang/@v/v0.0.0-20200831071321-c1fdfd3d6e7d.zip": dial tcp: lookup proxy.golang.org: no such host
咋解决~

**Comment by schaepher** [comment]
@FinchSaXY

https://goproxy.cn/

https://goproxy.io/zh/

这两个网站任意选一个按照它说的设置一下 GOPROXY。
